# -*- coding: utf-8 -*-
"""Gui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmL2QUAWg0XD5_r4WSFz_WgSQQMvmeoW
"""

#!pip install customtkinter
import sys
import os
import joblib
import customtkinter as ctk
import pandas as pd
import numpy as np
from tkinter import messagebox

# ----------------- Resource helper -----------------
def resource_path(rel_path):
    if getattr(sys, "frozen", False):
        base_path = sys._MEIPASS
    else:
        base_path = os.path.abspath(os.path.dirname(__file__))
    return os.path.join(base_path, rel_path)

# ----------------- Load model -----------------
#MODEL_PATH = "base_lgb.pkl"
MODEL_FILENAME = "base_lgb.pkl"
MODEL_PATH = resource_path(MODEL_FILENAME)

try:
    model = joblib.load(MODEL_PATH)
except Exception as e:
    messagebox.showerror("Model Error", f"Failed to load model at:\n{MODEL_PATH}\n\n{e}")
    raise SystemExit

# ----------------- Training data ranges -----------------
FEATURE_COLUMNS = [
    "TxLat", "TxLon", "RxLat", "RxLon",
    "TxHeight_m", "RxHeight_m", "TxPower_dBm", "Frequency_MHz"
]

feature_ranges = {
    "TxLat": (29.41821992971, 31.3462637023394),
    "TxLon": (77.0334108645892, 79.1403742584986),
    "RxLat": (29.4277240251956, 31.2298508213332),
    "RxLon": (77.11244502218, 79.1023703367367),
    "TxHeight_m": (1, 40),
    "RxHeight_m": (1, 40),
    "TxPower_dBm": (37, 48),
    "Frequency_MHz": (240, 412)
}

def validate_input_ranges(values):
    for i, col in enumerate(FEATURE_COLUMNS):
        min_v, max_v = feature_ranges[col]
        if values[i] < min_v or values[i] > max_v:
            messagebox.showerror(
                "Input Error",
                f"{col} out of range!\nAllowed: {min_v} to {max_v}\nYou entered: {values[i]}"
            )
            return False
    return True

# ----------------- UI Setup -----------------
ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")

app = ctk.CTk()
app.title("📡 RSSI Prediction + RFSoC Link")
app.geometry("560x760")

# ===== SCROLLABLE FRAME =====
scroll_frame = ctk.CTkScrollableFrame(app, width=520, height=600)
scroll_frame.pack(pady=10, padx=10, fill="both", expand=True)

labels = [
    "Tx Latitude", "Tx Longitude", "Rx Latitude", "Rx Longitude",
    "Tx Height (m)", "Rx Height (m)", "Tx Power (dBm)", "Frequency (MHz)"
]

entries = []

for i, text in enumerate(labels):
    ctk.CTkLabel(scroll_frame, text=text).pack(pady=(8 if i == 0 else 4, 2))
    ent = ctk.CTkEntry(scroll_frame, width=360)
    ent.pack()
    entries.append(ent)

    # Show allowed range below each input
    col = FEATURE_COLUMNS[i]
    min_v, max_v = feature_ranges[col]
    range_text = f"Allowed: {min_v} to {max_v}"
    ctk.CTkLabel(scroll_frame, text=range_text, font=ctk.CTkFont(size=11)).pack(pady=(1, 4))

default_values = [29.5, 77.5, 29.6, 77.6, 10, 5, 40, 300]
for e, v in zip(entries, default_values):
    e.insert(0, str(v))

# ----------------- Helper functions -----------------
def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371e3
    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)
    dphi = np.radians(lat2 - lat1)
    dlambda = np.radians(lon2 - lon1)
    a = np.sin(dphi / 2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(dlambda / 2)**2
    return R * 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

def calculate_azimuth(lat1, lon1, lat2, lon2):
    dlon = np.radians(lon2 - lon1)
    lat1_r = np.radians(lat1)
    lat2_r = np.radians(lat2)
    x = np.sin(dlon) * np.cos(lat2_r)
    y = np.cos(lat1_r) * np.sin(lat2_r) - np.sin(lat1_r) * np.cos(lat2_r) * np.cos(dlon)
    return (np.degrees(np.arctan2(x, y)) + 360) % 360

def calculate_elevation(tx_h, rx_h, distance_m):
    if distance_m == 0:
        return 0.0
    return np.degrees(np.arctan((tx_h - rx_h) / distance_m))

def normalize_expected_names(expected_iterable):
    return [str(x).replace("b'", "").replace("'", "") for x in expected_iterable]

# ----------------- Prediction -----------------
result_label = ctk.CTkLabel(app, text="", font=ctk.CTkFont(size=14, weight="bold"))
result_label.pack(pady=(6, 6))

def predict_and_optionally_send():
    try:
        values = [float(entries[i].get()) for i in range(8)]
    except Exception as e:
        messagebox.showerror("Input Error", f"Enter valid numeric values.\n{e}")
        return

    if not validate_input_ranges(values):
        return

    TxLat, TxLon, RxLat, RxLon, TxH, RxH, TxP, FreqMHz = values

    df = pd.DataFrame([{
        "TxLat": TxLat, "TxLon": TxLon,
        "RxLat": RxLat, "RxLon": RxLon,
        "TxHeight_m": TxH, "RxHeight_m": RxH,
        "TxPower_dBm": TxP, "Frequency_MHz": FreqMHz
    }])

    df["Distance_m"] = haversine_distance(TxLat, TxLon, RxLat, RxLon)
    df["Azimuth_deg"] = calculate_azimuth(TxLat, TxLon, RxLat, RxLon)
    df["Elevation_deg"] = calculate_elevation(TxH, RxH, float(df["Distance_m"].iloc[0]))
    df["Frequency_Hz"] = FreqMHz * 1e6

    eps = 1e-9
    df["Log_Distance"] = np.log(df["Distance_m"] + eps)
    df["Inv_Distance"] = 1 / (df["Distance_m"] + eps)
    df["FSPL_dB"] = (
        20 * np.log10((df["Distance_m"] / 1000) + eps)
        + 20 * np.log10(df["Frequency_MHz"] + eps)
        + 32.44
    )
    df["Height_Diff"] = df["TxHeight_m"] - df["RxHeight_m"]
    df["Height_Ratio"] = df["TxHeight_m"] / (df["RxHeight_m"] + eps)

    try:
        expected = getattr(model, "feature_names_in_", None)
        if expected is not None:
            expected_list = normalize_expected_names(expected)
            df_to_pred = df[expected_list]
        else:
            df_to_pred = df
    except Exception as e:
        messagebox.showerror("Feature Error", str(e))
        return

    # -------- SAFE PREDICTION  --------
    try:
        X = df_to_pred.to_numpy(dtype=np.float64)

        # Try normal predict first
        pred = model.predict(X)

        if isinstance(pred, np.ndarray):
            pred = float(pred[0])
        else:
            pred = float(pred)

    except Exception as e:
        try:
            # Backup LightGBM-safe method
            pred = model.booster_.predict(X)[0]
        except Exception as e2:
            messagebox.showerror(
                "Prediction Error",
                f"LightGBM EXE compatibility error.\n\n"
                f"Primary Error:\n{e}\n\n"
                f"Backup Error:\n{e2}"
            )
            return

    result_label.configure(text=f"Predicted RSSI: {pred:.2f} dBm")

# ===== BUTTON =====
ctk.CTkButton(app, text="Predict RSSI", command=predict_and_optionally_send).pack(pady=15)

if __name__ == "__main__":
    app.mainloop()
