name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install customtkinter pandas numpy joblib lightgbm

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --add-data "base_lgb.pkl;." gui.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: exe-file
        path: dist/gui.exe
