name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install libraries
      run: |
        pip install pyinstaller customtkinter pandas numpy joblib lightgbm

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --add-data "base_lgb.pkl;." gui.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: exe-file
        path: dist/
